"""created table 'user' as a test

Revision ID: a6e894febe80
Revises: 
Create Date: 2025-05-27 13:38:27.777412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e894febe80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sebank_customers_with_accounts')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_account', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_municipality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('receiver_municipality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('sebank_customers_with_accounts',
    sa.Column('Customer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Personnummer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('BankAccount', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
